version: 2.1
orbs:
  newman: postman/newman@0.0.2
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: <docker image>
    steps:
      - run: exit 0
      - slack/status:
          fail_only: true
          mentions:
          only_for_branches:
          webhook: '${SLACK_WEBHOOK}'
orbs:
  slack: circleci/slack@x.y.z
version: 2.1
      
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
       - checkout
       - newman/newman-run:
            collection: ./barrel_dex_collection.json
            environment: ./Barrel_QA.postman_environment.json

workflows:
  version: 2.1
  schedule-workflow: 
    triggers:
      - schedule:
          cron: "0 6,12,18,0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
  deploy:
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
