version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  newman: postman/newman@0.0.2
         
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
       - checkout
       - newman/newman-run:
            collection: ./Test.postman_collection.json
            environment: ./Barrel_QA.postman_environment.json
       - slack/status:
            webhook: 'https://hooks.slack.com/services/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'

workflows:
  version: 2.1
  schedule-workflow: 
    triggers:
      - schedule:
          cron: "0 6,12,18,0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
  deploy:
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
