version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
       - checkout
       - newman/newman-run:
            collection: ./DEX_DEV.postman_collection.json
            environment: ./DEV.postman_environment.json
workflows:
  version: 2.1
   schedule-workflow: 
    triggers:
      - schedule:
          cron: "0 6,12,18,0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
   deploy:
    jobs:
      - newman-collection-run:
          context: BarrelSandbox
